---
#- include: "level-1/1.1.1.1.yml"
#  when: "'1.1.1.1' not in cis_level_1_exclusions"
#- include: "level-1/1.1.1.2.yml"
#  when: "'1.1.1.2' not in cis_level_1_exclusions"
#- include: "level-1/1.1.1.3.yml"
#  when: "'1.1.1.3' not in cis_level_1_exclusions"
#- include: "level-1/1.1.1.4.yml"
#  when: "'1.1.1.4' not in cis_level_1_exclusions"
#- include: "level-1/1.1.1.5.yml"
#  when: "'1.1.1.5' not in cis_level_1_exclusions"
#- include: "level-1/1.1.1.6.yml"
#  when: "'1.1.1.6' not in cis_level_1_exclusions"
#- include: "level-1/1.1.1.7.yml"
#  when: "'1.1.1.7' not in cis_level_1_exclusions"
#- include: "level-1/1.1.1.8.yml"
#  when: "'1.1.1.8' not in cis_level_1_exclusions"
#- include: "level-1/1.1.15.yml"
#  when: "'1.1.15' not in cis_level_1_exclusions"
#- include: "level-1/1.1.16.yml"
#  when: "'1.1.16' not in cis_level_1_exclusions"
#- include: "level-1/1.1.17.yml"
#  when: "'1.1.17' not in cis_level_1_exclusions"
#- include: "level-1/1.2.3.yml"
#  when: "'1.2.3' not in cis_level_1_exclusions"
#- include: "level-1/1.3.1.yml"
#  when: "'1.3.1' not in cis_level_1_exclusions"
#- include: "level-1/1.3.2.yml"
#  when: "'1.3.2' not in cis_level_1_exclusions"
#- include: "level-1/1.4.1.yml"
#  when: "'1.4.1' not in cis_level_1_exclusions"
#- include: "level-1/1.5.1.yml"
#  when: "'1.5.1' not in cis_level_1_exclusions"
#- include: "level-1/1.5.3.yml"
#  when: "'1.5.3' not in cis_level_1_exclusions"
#- include: "level-1/3.1.1.yml"
#  when: "'3.1.1' not in cis_level_1_exclusions"
#- include: "level-1/3.1.2.yml"
#  when: "'3.1.2' not in cis_level_1_exclusions"
#- include: "level-1/3.2.1.yml"
#  when: "'3.2.1' not in cis_level_1_exclusions"
#- include: "level-1/3.2.2.yml"
#  when: "'3.2.2' not in cis_level_1_exclusions"
#- include: "level-1/3.2.3.yml"
#  when: "'3.2.3' not in cis_level_1_exclusions"
#- include: "level-1/3.2.4.yml"
#  when: "'3.2.4' not in cis_level_1_exclusions"
#- include: "level-1/3.2.5.yml"
#  when: "'3.2.5' not in cis_level_1_exclusions"
#- include: "level-1/3.2.6.yml"
#  when: "'3.2.6' not in cis_level_1_exclusions"
#- include: "level-1/3.2.7.yml"
#  when: "'3.2.7' not in cis_level_1_exclusions"
#- include: "level-1/3.2.8.yml"
#  when: "'3.2.8' not in cis_level_1_exclusions"
#- include: "level-1/3.3.1.yml"
#  when: "'3.3.1' not in cis_level_1_exclusions"
#- include: "level-1/3.3.2.yml"
#  when: "'3.3.2' not in cis_level_1_exclusions"
#- include: "level-1/3.3.3.yml"
#  when: "'3.3.3' not in cis_level_1_exclusions"
#- include: "level-1/3.5.1.yml"
#  when: "'3.5.1' not in cis_level_1_exclusions"
#- include: "level-1/3.5.2.yml"
#  when: "'3.5.2' not in cis_level_1_exclusions"
#- include: "level-1/3.5.3.yml"
#  when: "'3.5.3' not in cis_level_1_exclusions"
#- include: "level-1/3.5.4.yml"
#  when: "'3.5.4' not in cis_level_1_exclusions"
#- include: "level-1/3.6.1.yml"
#  when: "'3.6.1' not in cis_level_1_exclusions"
#- include: "level-2/4.1.yml"
#  when: "'4.1' not in cis_level_2_exclusions"
#- include: "level-2/4.1.2.yml"
#  when: "'4.1.2' not in cis_level_2_exclusions"
- include: "level-2/4.1.3.yml"
  when: "'4.1.3' not in cis_level_2_exclusions"
#- include: "level-2/4.1.n.yml"
#  when: "'4.1.n' not in cis_level_2_exclusions"
#- include: "level-1/4.2.1.1.yml"
#  when: "'4.2.1.1' not in cis_level_1_exclusions"
#- include: "level-1/4.2.1.3.yml"
#  when: "'4.2.1.3' not in cis_level_1_exclusions"
#- include: "level-1/5.1.1.yml"
#  when: "'5.1.1' not in cis_level_1_exclusions"
#- include: "level-1/5.1.2.yml"
#  when: "'5.1.2' not in cis_level_1_exclusions"
#- include: "level-1/5.1.3.yml"
#  when: "'5.1.3' not in cis_level_1_exclusions"
#- include: "level-1/5.1.4.yml"
#  when: "'5.1.4' not in cis_level_1_exclusions"
#- include: "level-1/5.1.5.yml"
#  when: "'5.1.5' not in cis_level_1_exclusions"
#- include: "level-1/5.1.6.yml"
#  when: "'5.1.6' not in cis_level_1_exclusions"
#- include: "level-1/5.1.7.yml"
#  when: "'5.1.7' not in cis_level_1_exclusions"
#- include: "level-1/5.2.1.yml"
#  when: "'5.2.1' not in cis_level_1_exclusions"
#- include: "level-1/5.2.2.yml"
#  when: "'5.2.2' not in cis_level_1_exclusions"
#- include: "level-1/5.2.3.yml"
#  when: "'5.2.3' not in cis_level_1_exclusions"
#- include: "level-1/5.2.4.yml"
#  when: "'5.2.4' not in cis_level_1_exclusions"
#- include: "level-1/5.2.5.yml"
#  when: "'5.2.5' not in cis_level_1_exclusions"
#- include: "level-1/5.2.6.yml"
#  when: "'5.2.6' not in cis_level_1_exclusions"
#- include: "level-1/5.2.7.yml"
#  when: "'5.2.7' not in cis_level_1_exclusions"
#- include: "level-1/5.2.8.yml"
#  when: "'5.2.8' not in cis_level_1_exclusions"
#- include: "level-1/5.2.9.yml"
#  when: "'5.2.9' not in cis_level_1_exclusions"
#- include: "level-1/5.2.10.yml"
#  when: "'5.2.10' not in cis_level_1_exclusions"
#- include: "level-1/5.2.11.yml"
#  when: "'5.2.11' not in cis_level_1_exclusions"
#- include: "level-1/5.2.12.yml"
#  when: "'5.2.12' not in cis_level_1_exclusions"
#- include: "level-1/5.2.13.yml"
#  when: "'5.2.13' not in cis_level_1_exclusions"
#- include: "level-1/5.2.14.yml"
#  when: "'5.2.14' not in cis_level_1_exclusions"
#- include: "level-1/5.2.16.yml"
#  when: "'5.2.16' not in cis_level_1_exclusions"
#- include: "level-1/5.3.1.yml"
#  when: "'5.3.1' not in cis_level_1_exclusions"
#- include: "level-1/5.3.2.yml"
#  when: "'5.3.2' not in cis_level_1_exclusions"
#- include: "level-1/5.3.4.yml"
#  when: "'5.3.4' not in cis_level_1_exclusions"
#- include: "level-1/5.4.1.1.yml"
#  when: "'5.4.1.1' not in cis_level_1_exclusions"
#- include: "level-1/5.4.1.2.yml"
#  when: "'5.4.1.2' not in cis_level_1_exclusions"
#- include: "level-1/5.4.1.3.yml"
#  when: "'5.4.1.3' not in cis_level_1_exclusions"
#- include: "level-1/5.4.3.yml"
#  when: "'5.4.3' not in cis_level_1_exclusions"
#- include: "level-1/5.4.4.yml"
#  when: "'5.4.4' not in cis_level_1_exclusions"
#- include: "level-1/6.1.2.yml"
#  when: "'6.1.2' not in cis_level_1_exclusions"
#- include: "level-1/6.1.3.yml"
#  when: "'6.1.3' not in cis_level_1_exclusions"
#- include: "level-1/6.1.4.yml"
#  when: "'6.1.4' not in cis_level_1_exclusions"
#- include: "level-1/6.1.5.yml"
#  when: "'6.1.5' not in cis_level_1_exclusions"
