# Standards: 1.1.28
---

# 4.1.3 Ensure auditing for processes that start prior to auditd is enabled

- name: 4.1.3 - Ensure auditing for processes that start prior to auditd is enabled
  copy:
    src: "/etc/default/grub"
    dest: /tmp
    owner: root 
    group: root 
    mode: 'preserve'
    remote_src: true
  when: rollback is not defined
  tags:
    - level-2
    - section-4
    - "4.1.3"
    - scored

- name: 4.1.3 - Ensure auditing for processes that start prior to auditd is enabled
  lineinfile:
    regexp: "^GRUB_CMDLINE_LINUX="
    line: 'GRUB_CMDLINE_LINUX="console=ttyS0,115200n8 console=tty0 net.ifnames=0 crashkernel=auto audit=1"'
    state: present
    dest: "/etc/default/grub"
    backup: yes
  when: rollback is not defined
  tags:
    - level-2
    - section-4
    - "4.1.3"
    - scored

- name: 4.1.3 - (rollback)Ensure auditing for processes that start prior to auditd is enabled
  copy:
    src: /tmp/grub
    dest: /etc/default/grub
    owner: root 
    group: root 
    mode: 'preserve'
    remote_src: true
  when: rollback is defined
  tags:
    - level-2
    - section-4
    - "4.1.3"
    - scored

- name: 4.1.3 - Run the command to update the Grub Configuration
  command: "grub2-mkconfig > /boot/grub2/grub.cfg"
  changed_when: false
  when: rollback is not defined or rollback is defined
  tags:
    - level-2
    - section-4
    - "4.1.3"
    - scored
