# Standards: 0.11
---

# 1.3.1 Ensure AIDE is installed

- name: 1.3.1 - Ensure AIDE is installed
  yum:
    name: aide
    state: present
  when: rollback is not defined
  tags:
    - level-1
    - section-1
    - "1.3.1"
    - scored


- name: 1.3.1 - Check that aide database exists
  stat:
    path: "{{ cis_aide_database_filename }}"
  register: aide_1_3_1
  when: rollback is not defined
  tags:
    - level-1
    - section-1
    - "1.3.1"
    - scored

# We expect that 'aide --init' has been run and the generated database has been moved
- name: 1.3.1 - Ensure aide database exists
  command: "{{ item }}"
  ignore_errors: true
  with_items:
    - "aide --init"
    - "mv {{ cis_aide_src_database_filename }} {{ cis_aide_database_filename }}"
  when: aide_1_3_1.stat.exists is not defined or not aide_1_3_1.stat.exists or rollback is not defined
  tags:
    - level-1
    - section-1
    - "1.3.1"
    - scored

- name: 1.3.1 - (rollback)Ensure aide database is rollback 
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ cis_aide_src_database_filename }}" 
    - "{{ cis_aide_database_filename }}"
  when: rollback is defined
  tags:
    - level-1
    - section-1
    - "1.3.1"
    - scored

- name: 1.3.1 - (rollback)Ensure AIDE is removed
  yum:
    name: aide
    state: absent 
  when: rollback is defined
  tags:
    - level-1
    - section-1
    - "1.3.1"
    - scored
