# Standards: 0.11
---

# 4.2.1.3 Ensure rsyslog default file permissions configured

- name: 4.2.1.3 - Ensure rsyslog default file permissions configured
  lineinfile:
    regexp: "^\\$FileCreateMode\\s+"
    line: "$FileCreateMode 0640"
    insertbefore: BOF
    dest: "/etc/rsyslog.conf"
  when: cis_enable_rsyslog and rollback is not defined
  notify:
    - Restart rsyslog
  tags:
    - level-1
    - section-4
    - "4.2.1.3"
    - scored

- name: 4.2.1.3 - (rollback)Ensure rsyslog default file permissions configured
  lineinfile:
    path: "/etc/rsyslog.conf"
    regexp: "^\\$FileCreateMode\\s+"
    line: "$FileCreateMode 0640"
    state: absent
  when: rollback is defined
  notify:
    - Restart rsyslog
  tags:
    - level-1
    - section-4
    - "4.2.1.3"
    - scored
