# Standards: 0.11
---

# 5.1.7 Ensure permissions on /etc/cron.d are configured

- name: 5.1.7 - Ensure permissions on /etc/cron.d are configured
  file:
    path: "/etc/cron.d"
    owner: root
    group: root
    mode: 0600
    state: directory
  when: rollback is not defined
  tags:
    - level-1
    - section-5
    - "5.1.7"
    - scored

- name: 5.1.7 - (rollback)Ensure permissions on /etc/cron.d are configured
  file:
    path: "/etc/cron.d"
    owner: root
    group: root
    mode: 0755
    state: directory
  when: rollback is defined
  tags:
    - level-1
    - section-5
    - "5.1.7"
    - scored
