# Standards: 0.11
---

# 5.2.11 - Ensure only approved ciphers are used

- include: stat_sshd_config.yml
  tags:
    - level-1
    - section-5
    - "5.2.11"
    - scored

- name: 5.2.11 - Ensure only approved ciphers are used
  lineinfile:
    regexp: "^Ciphers\\s+"
    line: "Ciphers {{ cis_sshd_ciphers }}"
    dest: "/etc/ssh/sshd_config"
  when: sshd_config.stat.exists and rollback is not defined
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - "5.2.11"
    - scored

- name: 5.2.11 - (rollback)Ensure only approved ciphers are used
  lineinfile:
    regexp: "^Ciphers\\s+"
    line: "#Ciphers {{ cis_sshd_ciphers }}"
    dest: "/etc/ssh/sshd_config"
  when: rollback is defined
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - "5.2.11"
    - scored
