# Standards: 0.11
---

# 5.2.4 - Ensure SSH X11 forwarding is disabled

- include: stat_sshd_config.yml
  tags:
    - level-1
    - section-5
    - "5.2.4"
    - scored

- name: 5.2.4 - Ensure SSH X11 forwarding is disabled
  lineinfile:
    regexp: "^X11Forwarding\\s+"
    line: "X11Forwarding no"
    dest: "/etc/ssh/sshd_config"
  when: sshd_config.stat.exists and rollback is not defined
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - "5.2.4"
    - scored

- name: 5.2.4 - (rollback)Ensure SSH X11 forwarding is disabled
  lineinfile:
    regexp: "^X11Forwarding\\s+"
    line: "X11Forwarding yes"
    dest: "/etc/ssh/sshd_config"
  when: rollback is defined
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - "5.2.4"
    - scored
